name: Build and deploy Python project to Azure Function App - matrixmultiplication

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Vendor dependencies into .python_packages
        shell: bash
        run: |
          rm -rf .python_packages
          mkdir -p .python_packages/lib/site-packages
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt --target ".python_packages/lib/site-packages"
          export PYTHONPATH="$PWD/.python_packages/lib/site-packages:$PYTHONPATH"
          python -c "import os, sys; print('PYTHONPATH_OK', os.path.exists('.python_packages/lib/site-packages'))"
          python -c "import os, numpy as np; print('VENDORED_NUMPY', np.__version__); print('HAS_NUMPY_FILE', os.path.exists('.python_packages/lib/site-packages/numpy/__init__.py'))"


      - name: Sanity list
        shell: bash
        run: |
          echo "== function.json files =="
          find . -maxdepth 3 -name function.json -print
          echo "== site-packages head =="
          ls -la .python_packages/lib/site-packages | head -n 50 || true

      - name: Prepare deploy folder
        shell: bash
        run: |
          rm -rf app
          mkdir app
          shopt -s dotglob
          cp -r * app/
          rm -rf app/venv app/.git app/.github

      - name: Archive app
        shell: bash
        run: zip -qr app.zip app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp

      - name: Unzip artifact for deployment
        shell: bash
        run: |
          unzip -q app.zip -d .
          echo "== root of app =="
          ls -la app | head -n 100
          echo "== has .python_packages =="
          ls -la app/.python_packages/lib/site-packages | head -n 50 || true

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: matrixmultiplication
          package: "app"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FA63582491A245C28606470E7AC07179 }}
